[pr_reviewer]
enable_review_labels_effort = true
enable_auto_approval = true

[github_app]
pr_commands = [
    "/describe --pr_description.publish_description_as_comment=true",
    "/improve",
    "/review"
]

handle_push_trigger = true
push_commands = [
    "/improve",
    "/review"
]
