# Copy this file to .secrets.toml and fill in your API keys
# Add .secrets.toml to your .gitignore to keep credentials secure

[openai]
key = "your-openai-api-key-here"  # Required for embeddings and analysis

[pinecone]
api_key = "your-pinecone-api-key-here"  # Required for vector database
environment = "gcp-starter"  # Or your Pinecone environment (e.g., "us-west1-gcp-free")

[config]
# Other optional settings
# github.personal_access_token = "your-github-token"  # Only if you want GitHub integration