name: 'Custom PR Agent (Minimax)'
description: 'PR reviews using Minimax/Anthropic-compatible LLM'
branding:
  icon: 'award'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/owen26/pr-agent:latest'
