apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pr-agent.fullname" . }}
  labels:
    {{- include "pr-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pr-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "pr-agent.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pr-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "pr-agent.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- include "pr-agent.command" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            # Core configuration environment variables
            {{- include "pr-agent.configEnvVars" . | nindent 12 }}
            # Secret environment variables
            {{- include "pr-agent.secretEnvVars" . | nindent 12 }}
            # Additional custom environment variables
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # Deployment mode specific variables
            {{- if eq .Values.deploymentMode "github_app" }}
            - name: GITHUB__DEPLOYMENT_TYPE
              value: "app"
            {{- else if eq .Values.deploymentMode "gitlab_webhook" }}
            - name: GITLAB__DEPLOYMENT_TYPE
              value: "webhook"
            {{- end }}
            # Python path
            - name: PYTHONPATH
              value: "/app"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.configOverride }}
            - name: config-volume
              mountPath: /app/pr_agent/settings_prod
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.configOverride }}
        - name: config-volume
          configMap:
            name: {{ include "pr-agent.fullname" . }}-config
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 