{{- $hasSecrets := false -}}
{{- range $key, $value := .Values.secrets -}}
  {{- if $value -}}
    {{- $hasSecrets = true -}}
  {{- end -}}
{{- end -}}
{{- if $hasSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pr-agent.fullname" . }}-secrets
  labels:
    {{- include "pr-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openai_key }}
  openai-key: {{ .Values.secrets.openai_key | b64enc }}
  {{- end }}
  {{- if .Values.secrets.github_token }}
  github-token: {{ .Values.secrets.github_token | b64enc }}
  {{- end }}
  {{- if .Values.secrets.github_webhook_secret }}
  github-webhook-secret: {{ .Values.secrets.github_webhook_secret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.github_app_id }}
  github-app-id: {{ .Values.secrets.github_app_id | b64enc }}
  {{- end }}
  {{- if .Values.secrets.github_private_key }}
  github-private-key: {{ .Values.secrets.github_private_key | b64enc }}
  {{- end }}
  {{- if .Values.secrets.anthropic_key }}
  anthropic-key: {{ .Values.secrets.anthropic_key | b64enc }}
  {{- end }}
  {{- if .Values.secrets.google_ai_studio_gemini_api_key }}
  google-ai-studio-gemini-api-key: {{ .Values.secrets.google_ai_studio_gemini_api_key | b64enc }}
  {{- end }}
{{- end }} 