apiVersion: v1
kind: Service
metadata:
  name: {{ include "pr-agent.fullname" . }}
  labels:
    {{- include "pr-agent.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pr-agent.selectorLabels" . | nindent 4 }}
