#!/usr/bin/env python3
"""
Production entrypoint script for PR Agent.

Loads secrets from Google Cloud Secret Manager and generates .secrets.toml
before starting the server.

Usage:
    python scripts/entrypoint.py [command]
    
Examples:
    python scripts/entrypoint.py gunicorn
    python scripts/entrypoint.py uvicorn
"""

import os
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
SETTINGS_DIR = PROJECT_ROOT / "pr_agent" / "settings"
SECRETS_FILE = SETTINGS_DIR / ".secrets.toml"


def load_secrets_from_env() -> dict[str, str]:
    """Extract secrets from environment variables."""
    return {
        "GITHUB_APP_ID": os.environ.get("GITHUB_APP_ID", ""),
        "GITHUB_APP_PRIVATE_KEY": os.environ.get("GITHUB_APP_PRIVATE_KEY", ""),
        "GITHUB_WEBHOOK_SECRET": os.environ.get("GITHUB_WEBHOOK_SECRET", ""),
        "GOOGLE_API_KEY": os.environ.get("GOOGLE_API_KEY", ""),
        "OPENAI_API_KEY": os.environ.get("OPENAI_API_KEY", ""),
        "ANTHROPIC_API_KEY": os.environ.get("ANTHROPIC_API_KEY", ""),
        "JIRA_API_TOKEN": os.environ.get("JIRA_API_TOKEN", ""),
        "FIGMA_ACCESS_TOKEN": os.environ.get("FIGMA_ACCESS_TOKEN", ""),
    }


def load_secrets_from_secret_manager() -> dict[str, str]:
    """Load secrets from Google Cloud Secret Manager."""
    project_id = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
    env_name = os.environ.get("ENV", "development")
    
    if not project_id:
        print("GOOGLE_CLOUD_PROJECT not set, skipping Secret Manager")
        return {}
    
    try:
        sys.path.insert(0, str(PROJECT_ROOT))
        from pr_agent.utils.config_loader import load_config_sync
        
        config = load_config_sync(
            project_id=project_id,
            service_name="pr-agent",
            env_name_override=env_name,
            update_environ=True,
        )
        return config
    except Exception as e:
        print(f"Warning: Failed to load from Secret Manager: {e}")
        return {}


def generate_secrets_toml(secrets: dict[str, str]) -> None:
    """Generate .secrets.toml file from secrets dictionary."""
    github_private_key = secrets.get("GITHUB_APP_PRIVATE_KEY", "")
    if github_private_key.startswith("base64:"):
        import base64
        github_private_key = base64.b64decode(github_private_key[7:]).decode()
    
    toml_content = f'''# Auto-generated secrets file - DO NOT COMMIT
# Generated by scripts/entrypoint.py

[google_ai_studio]
gemini_api_key = "{secrets.get("GOOGLE_API_KEY", "")}"

[openai]
key = "{secrets.get("OPENAI_API_KEY", "")}"

[anthropic]
key = "{secrets.get("ANTHROPIC_API_KEY", "")}"

[github]
deployment_type = "app"
app_id = {secrets.get("GITHUB_APP_ID", "0")}
webhook_secret = "{secrets.get("GITHUB_WEBHOOK_SECRET", "")}"
private_key = """
{github_private_key}
"""

[config]
model = "gemini/gemini-3-pro"
fallback_models = ["gemini/gemini-2.5-pro"]
'''
    
    SECRETS_FILE.write_text(toml_content)
    print(f"Generated {SECRETS_FILE}")


def main() -> None:
    env_name = os.environ.get("ENV", "development")
    print(f"Starting PR Agent in {env_name} mode")
    
    if not SECRETS_FILE.exists():
        print("No .secrets.toml found, generating from secrets...")
        
        secrets = load_secrets_from_env()
        
        if env_name != "development":
            sm_secrets = load_secrets_from_secret_manager()
            secrets.update(sm_secrets)
        
        generate_secrets_toml(secrets)
    else:
        print(f"Using existing {SECRETS_FILE}")
    
    if len(sys.argv) < 2:
        print("No command specified, use 'gunicorn' or 'uvicorn'")
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "gunicorn":
        cmd = [
            "python", "-m", "gunicorn",
            "-k", "uvicorn.workers.UvicornWorker",
            "-c", "pr_agent/servers/gunicorn_config.py",
            "--forwarded-allow-ips", "*",
            "pr_agent.servers.github_app:app"
        ]
    elif command == "uvicorn":
        port = os.environ.get("PORT", "8000")
        cmd = [
            "python", "-m", "uvicorn",
            "pr_agent.servers.github_app:app",
            "--host", "0.0.0.0",
            "--port", port
        ]
    else:
        cmd = sys.argv[1:]
    
    print(f"Executing: {' '.join(cmd)}")
    os.execvp(cmd[0], cmd)


if __name__ == "__main__":
    main()
